---
- name: Provision AWS resources
  hosts: localhost
  tasks:
    - name: Launch EC2 instance
      ec2:
        key_name: your_key_pair
        instance_type: t2.micro
        image: ami-0c55b159cbfafe1f0
        wait: yes
        region: us-east-1
        group: default
        count: 1
        instance_tags:
          Name: WebAppServer
        vpc_subnet_id: subnet-xxxxxx
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: aws
      with_items: "{{ ec2.instances }}"
